### ISSUE TITLE
Using REST api in the debugger

### ISSUE THREAD

**Issue by amodaresi** [mariusciocan/parse-cloud-debugger#22]
@mariusciocan 
How should I test the REST api?
When I test the curl command on localhost:5555 in terminal nothing happens and it seems that the requests that I enter just timeout.
Does it needs any changes for the REST api?

And another thing, does this debugger support saving objects and creating queries? And if does, Is there anyway to see the tables in my local system?

**Comment by mariusciocan** [comment]
Please take a look at this file: https://raw.githubusercontent.com/mariusciocan/parse-cloud-debugger/master/parse-cloud-code-demo/public/javascripts/demo.js

This is the javascript file used for tutorial which also can be found here: http://parse-cloud-debbuger.parseapp.com.

You should use the Parse.run function to call the REST api.
